[project]
name = "pqcdbchk"
version = "0.1.0"
description = "A Jupyter notebook and Python-based tool for exporting, searching, and editing PHREEQC databases"
readme = "README.md"
authors = [
    { name = "name", email = "email" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.4.2",
    "matplotlib>=3.11.0",
    "numpy>=2.5.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
]
docs = [
    "furo>=2025.12.19",
    "myst-parser>=5.1.0",
    "sphinx>=9.1.0",
]

[tool.pytest.ini_options]
addopts = "-v -n auto --doctest-modules --cov=pqcdbchk --cov-report=html --cov-report=term tests/"
